version: '3.8'
services:
  point-api:
    image: point-api
    container_name: point-api
    depends_on:
      - "database"
  ranking-api:
    image: ranking-api
    container_name: ranking-api
    depends_on:
      - "database"
  webapp:
    image: mela-next
    container_name: mela-next
    depends_on:
      - "point-api"
      - "ranking-api"
  webserver:
    image: webserver
    container_name: webserver
    ports:
      - "80:80"
    depends_on:
      - "webapp"
    restart: always
