version: 3

tasks:
  dry-run:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml up --dry-run
  build:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml build
  run:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml up -d
  stop:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml down
  dynamodb-up:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml up -d dynamodb-local dynamo-admin
  dynamodb-down:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml down dynamodb-local dynamo-admin