version: 3

tasks:
  dry-run:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml up --dry-run
  build:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml build
  run:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml up -d
  stop:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-dev.yml down
  dynamodb-up:
    cmds:
      - docker run --rm -d -p 8000:8000 --name dynamodb amazon/dynamodb-local
  dynamodb-down:
    cmds:
      - docker stop dynamodb
  dynamodb-setup:
    cmds:
      - aws dynamodb create-table --region us-east-1 --table-name content --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName="id",KeyType="HASH" --billing-mode PAY_PER_REQUEST --endpoint-url $DYNAMO_ENDPOINT
      - aws dynamodb create-table --region us-east-1 --table-name user --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName="id",KeyType="HASH" --billing-mode PAY_PER_REQUEST --endpoint-url $DYNAMO_ENDPOINT
      - aws dynamodb create-table --region us-east-1 --table-name spending --attribute-definitions AttributeName=content_id,AttributeType=S AttributeName=user_id,AttributeType=S  --key-schema AttributeName="content_id",KeyType="HASH" AttributeName="user_id",KeyType="RANGE" --billing-mode PAY_PER_REQUEST --endpoint-url $DYNAMO_ENDPOINT