on:
  push:
    brancheds:
      main
    path:
      - "api/point-api/**"
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/point-api
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setupg-go@v4
        with:
          go-version: 1.21.5
      - name: Run test
        run: |
          go test
    