name: cd
run-name: ${{ github.actor }} is deploying
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        array: [
          number: {dockerBuildContext: "./api/point-api/", ecrRepository: "mela/point-api"},
          number: {dockerBuildContext: "./api/ranking-api/", ecrRepository: "mela/ranking-api"},
          number: {dockerBuildContext: "./web/mela-next/", ecrRepository: "mela/mela-next"},
          number: {dockerBuildContext: "./web/server/", ecrRepository: "mela/webserver"}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # TODO: skip non-changed path
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.array.number.dockerBuildContext }}
          platforms: linux/amd64
          push: true
          tags:
            ${{ env.ECR_REGISTRY }}/${{ matrix.array.number.ecrRepository }}:latest
