name: point-api-deploy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api/point-api/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Install ecspresso
        uses: kayac/ecspresso@v2
        with:
          version: v2.3.1
      - name: Deploy
        run: |
          ecspresso deploy