on:
  push:
    branches:
      - develop
    paths:
      - "api/point-api/**"
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/point-api
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      - name: Run test
        run: |
          go test
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
