name: point-api-ci
on:
  push:
    branches:
      - develop
    paths:
      - "api/point-api/**"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/point-api
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      - name: Run test
        run: |
          go test
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
